---
repos:
  # --- Python Linting ---
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args: [--max-line-length=100]

  # --- Autoformat Python with yapf ---
  - repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
      - id: yapf

  # --- Sort Imports with isort ---
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort

  # --- ESLint for Frontend ---
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.23.0
    hooks:
      - id: eslint
        name: ESLint (Frontend)
        files: ^frontend/
        args: [--fix, --config=./frontend/eslint.config.js]
        language: node
        language_version: 22.14.0
        pass_filenames: false
        require_serial: true
        verbose: true
        additional_dependencies:
          - eslint@9.22.0
          - '@eslint/js@9.22.0'
          - eslint-plugin-react@7.37.4
          - eslint-plugin-react-hooks@5.2.0
          - eslint-plugin-react-refresh@0.4.19
          - globals@16.0.0
          - react@19.0.0
          - react-dom@19.0.0

  # --- Prettier for non-JS/TS ---
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(json|md|yaml|yml)$
        types: [json, markdown, yaml]

  # --- YAML Linting ---
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$

  # --- General Git Hygiene ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        files: \.(yaml|yml)$
      - id: check-json
        files: \.json$
