repos:
  # --- Python Linting ---
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.2
    hooks:
      - id: flake8
        args: [--max-line-length=100]

  # --- Autoformat Python with yapf ---
  - repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
      - id: yapf

  # --- Sort Imports with isort ---
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort

  # --- ESLint for Frontend ---
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.22.0
    hooks:
      - id: eslint
        name: ESLint (Frontend)
        files: ^frontend/
        args: [--fix, --config=./frontend/eslint.config.js]
        types_or: [javascript, jsx]
        language: node
        additional_dependencies:
          - npm:eslint@9.22.0
          - npm:@eslint/js@9.22.0
          - npm:eslint-plugin-react@7.37.4
          - npm:eslint-plugin-react-hooks@5.2.0
          - npm:eslint-plugin-react-refresh@0.4.19
          - npm:globals@16.0.0

  # --- Prettier for non-JS/TS ---
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [json, markdown, yaml]
        files: \.(json|md|yaml)$

  # --- YAML Linting ---
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.36.1
    hooks:
      - id: yamllint
        types: [yaml]
        files: \.(yaml|yml)$

  # --- General Git Hygiene ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        files: \.(yaml|yml)$
      - id: check-json
        files: \.json$
