version: "3.9"

services:
  backend:
    build: .
    container_name: backend_app
    ports:
      - "8000:8000"
    env_file:
      - .env  # Load environment variables from .env
    volumes:
      - .:/app
